export const countries = ["India", "UAE", "USA", "UK", "Canada"];
export const mockQuotes = [
  {
    id: 1,
    courier: "DHL",
    price: 120,
    delivery: "3-5 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "USA",
    toCountry: "UK",
  },
  {
    id: 2,
    courier: "FedEx",
    price: 110,
    delivery: "4-6 days",
    discount: "5%",
    speed: "Standard",
    insurance: "$4",
    fromCountry: "USA",
    toCountry: "UK",
  },
  {
    id: 3,
    courier: "UPS",
    price: 130,
    delivery: "3-4 days",
    discount: "15%",
    speed: "Fast",
    insurance: "$6",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 4,
    courier: "TNT",
    price: 100,
    delivery: "5-7 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$3",
    fromCountry: "Canada",
    toCountry: "UK",
  },
  {
    id: 5,
    courier: "Aramex",
    price: 140,
    delivery: "2-4 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "India",
  },
  {
    id: 6,
    courier: "DHL",
    price: 115,
    delivery: "4-5 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$5",
    fromCountry: "India",
    toCountry: "UK",
  },
  {
    id: 7,
    courier: "FedEx",
    price: 105,
    delivery: "5-6 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$4",
    fromCountry: "India",
    toCountry: "UAE",
  },
  {
    id: 8,
    courier: "UPS",
    price: 125,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "USA",
  },
  {
    id: 9,
    courier: "TNT",
    price: 135,
    delivery: "4-6 days",
    discount: "9%",
    speed: "Standard",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "Canada",
  },
  {
    id: 10,
    courier: "Aramex",
    price: 95,
    delivery: "5-7 days",
    discount: "4%",
    speed: "Economy",
    insurance: "$3",
    fromCountry: "USA",
    toCountry: "UK",
  },
  {
    id: 11,
    courier: "DHL",
    price: 150,
    delivery: "2-3 days",
    discount: "5%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UAE",
    toCountry: "USA",
  },
  {
    id: 12,
    courier: "FedEx",
    price: 160,
    delivery: "3-4 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "UK",
    toCountry: "Canada",
  },
  {
    id: 13,
    courier: "UPS",
    price: 140,
    delivery: "4-5 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "India",
    toCountry: "UAE",
  },
  {
    id: 14,
    courier: "TNT",
    price: 130,
    delivery: "5-6 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$4",
    fromCountry: "Canada",
    toCountry: "USA",
  },
  {
    id: 15,
    courier: "Aramex",
    price: 155,
    delivery: "3-4 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 16,
    courier: "DHL",
    price: 165,
    delivery: "2-4 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 17,
    courier: "FedEx",
    price: 125,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 18,
    courier: "UPS",
    price: 135,
    delivery: "4-6 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 19,
    courier: "TNT",
    price: 145,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 20,
    courier: "Aramex",
    price: 155,
    delivery: "4-5 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UAE",
    toCountry: "Canada",
  },
  {
    id: 21,
    courier: "DHL",
    price: 115,
    delivery: "5-7 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "USA",
  },
  {
    id: 22,
    courier: "FedEx",
    price: 130,
    delivery: "3-5 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "India",
    toCountry: "UK",
  },
  {
    id: 23,
    courier: "UPS",
    price: 120,
    delivery: "4-5 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$4",
    fromCountry: "UAE",
    toCountry: "India",
  },
  {
    id: 24,
    courier: "TNT",
    price: 110,
    delivery: "5-6 days",
    discount: "4%",
    speed: "Economy",
    insurance: "$3",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 25,
    courier: "Aramex",
    price: 140,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "UK",
    toCountry: "UAE",
  },
  {
    id: 26,
    courier: "DHL",
    price: 150,
    delivery: "2-3 days",
    discount: "5%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "USA",
  },
  {
    id: 27,
    courier: "FedEx",
    price: 160,
    delivery: "3-4 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "USA",
    toCountry: "UK",
  },
  {
    id: 28,
    courier: "UPS",
    price: 140,
    delivery: "4-5 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "India",
    toCountry: "Canada",
  },
  {
    id: 29,
    courier: "TNT",
    price: 130,
    delivery: "5-6 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$4",
    fromCountry: "UK",
    toCountry: "USA",
  },
  {
    id: 30,
    courier: "Aramex",
    price: 155,
    delivery: "3-4 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "India",
  },
  {
    id: 31,
    courier: "DHL",
    price: 165,
    delivery: "2-4 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 32,
    courier: "FedEx",
    price: 125,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 33,
    courier: "UPS",
    price: 135,
    delivery: "4-6 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 34,
    courier: "TNT",
    price: 145,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 35,
    courier: "Aramex",
    price: 155,
    delivery: "4-5 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UAE",
    toCountry: "Canada",
  },
  {
    id: 36,
    courier: "DHL",
    price: 115,
    delivery: "5-7 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "USA",
  },
  {
    id: 37,
    courier: "FedEx",
    price: 130,
    delivery: "3-5 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "India",
    toCountry: "UK",
  },
  {
    id: 38,
    courier: "UPS",
    price: 120,
    delivery: "4-5 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$4",
    fromCountry: "UAE",
    toCountry: "India",
  },
  {
    id: 39,
    courier: "TNT",
    price: 110,
    delivery: "5-6 days",
    discount: "4%",
    speed: "Economy",
    insurance: "$3",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 40,
    courier: "Aramex",
    price: 140,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "UK",
    toCountry: "UAE",
  },
  {
    id: 41,
    courier: "DHL",
    price: 150,
    delivery: "2-3 days",
    discount: "5%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "USA",
  },
  {
    id: 42,
    courier: "FedEx",
    price: 160,
    delivery: "3-4 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "USA",
    toCountry: "UK",
  },
  {
    id: 43,
    courier: "UPS",
    price: 140,
    delivery: "4-5 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "India",
    toCountry: "Canada",
  },
  {
    id: 44,
    courier: "TNT",
    price: 130,
    delivery: "5-6 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$4",
    fromCountry: "UK",
    toCountry: "USA",
  },
  {
    id: 45,
    courier: "Aramex",
    price: 155,
    delivery: "3-4 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "India",
  },
  {
    id: 46,
    courier: "DHL",
    price: 165,
    delivery: "2-4 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 47,
    courier: "FedEx",
    price: 125,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 48,
    courier: "UPS",
    price: 135,
    delivery: "4-6 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 49,
    courier: "TNT",
    price: 145,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 50,
    courier: "Aramex",
    price: 155,
    delivery: "4-5 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UAE",
    toCountry: "Canada",
  },
  {
    id: 51,
    courier: "DHL",
    price: 160,
    delivery: "2-3 days",
    discount: "8%",
    speed: "Fast",
    insurance: "$9",
    fromCountry: "India",
    toCountry: "UAE",
  },
  {
    id: 52,
    courier: "FedEx",
    price: 145,
    delivery: "3-4 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "USA",
  },
  {
    id: 53,
    courier: "UPS",
    price: 135,
    delivery: "4-5 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$8",
    fromCountry: "USA",
    toCountry: "UK",
  },
  {
    id: 54,
    courier: "TNT",
    price: 125,
    delivery: "5-6 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$6",
    fromCountry: "UK",
    toCountry: "Canada",
  },
  {
    id: 55,
    courier: "Aramex",
    price: 150,
    delivery: "3-4 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "India",
  },
  {
    id: 56,
    courier: "DHL",
    price: 170,
    delivery: "2-3 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$9",
    fromCountry: "India",
    toCountry: "UK",
  },
  {
    id: 57,
    courier: "FedEx",
    price: 160,
    delivery: "3-5 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$8",
    fromCountry: "UAE",
    toCountry: "Canada",
  },
  {
    id: 58,
    courier: "UPS",
    price: 140,
    delivery: "4-5 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "USA",
    toCountry: "India",
  },
  {
    id: 59,
    courier: "TNT",
    price: 130,
    delivery: "5-7 days",
    discount: "6%",
    speed: "Economy",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "UAE",
  },
  {
    id: 60,
    courier: "Aramex",
    price: 155,
    delivery: "3-4 days",
    discount: "11%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "USA",
  },
  {
    id: 61,
    courier: "DHL",
    price: 165,
    delivery: "2-3 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$9",
    fromCountry: "India",
    toCountry: "Canada",
  },
  {
    id: 62,
    courier: "FedEx",
    price: 150,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 63,
    courier: "UPS",
    price: 145,
    delivery: "4-5 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$6",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 64,
    courier: "TNT",
    price: 135,
    delivery: "5-6 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 65,
    courier: "Aramex",
    price: 155,
    delivery: "3-4 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 66,
    courier: "DHL",
    price: 175,
    delivery: "2-3 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$10",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 67,
    courier: "FedEx",
    price: 165,
    delivery: "3-4 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "UAE",
    toCountry: "Canada",
  },
  {
    id: 68,
    courier: "UPS",
    price: 155,
    delivery: "4-5 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "USA",
    toCountry: "UK",
  },
  {
    id: 69,
    courier: "TNT",
    price: 145,
    delivery: "5-7 days",
    discount: "6%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "UK",
    toCountry: "USA",
  },
  {
    id: 70,
    courier: "Aramex",
    price: 160,
    delivery: "3-4 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "India",
  },
  {
    id: 71,
    courier: "DHL",
    price: 150,
    delivery: "2-3 days",
    discount: "8%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "India",
    toCountry: "UAE",
  },
  {
    id: 72,
    courier: "FedEx",
    price: 140,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 73,
    courier: "UPS",
    price: 130,
    delivery: "4-5 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$6",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 74,
    courier: "TNT",
    price: 120,
    delivery: "5-6 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 75,
    courier: "Aramex",
    price: 135,
    delivery: "3-4 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 76,
    courier: "DHL",
    price: 160,
    delivery: "2-3 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 77,
    courier: "FedEx",
    price: 155,
    delivery: "3-4 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "Canada",
  },
  {
    id: 78,
    courier: "UPS",
    price: 145,
    delivery: "4-5 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$6",
    fromCountry: "USA",
    toCountry: "UK",
  },
  {
    id: 79,
    courier: "TNT",
    price: 135,
    delivery: "5-7 days",
    discount: "6%",
    speed: "Economy",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "Canada",
  },
  {
    id: 80,
    courier: "Aramex",
    price: 150,
    delivery: "3-4 days",
    discount: "11%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "Canada",
    toCountry: "India",
  },
  {
    id: 81,
    courier: "DHL",
    price: 170,
    delivery: "2-3 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$9",
    fromCountry: "India",
    toCountry: "UK",
  },
  {
    id: 82,
    courier: "FedEx",
    price: 160,
    delivery: "3-4 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$8",
    fromCountry: "UAE",
    toCountry: "USA",
  },
  {
    id: 83,
    courier: "UPS",
    price: 150,
    delivery: "4-5 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 84,
    courier: "TNT",
    price: 140,
    delivery: "5-6 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$6",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 85,
    courier: "Aramex",
    price: 155,
    delivery: "3-4 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 86,
    courier: "DHL",
    price: 175,
    delivery: "2-3 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$10",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 87,
    courier: "FedEx",
    price: 165,
    delivery: "3-4 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 88,
    courier: "UPS",
    price: 155,
    delivery: "4-5 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 89,
    courier: "TNT",
    price: 145,
    delivery: "5-7 days",
    discount: "6%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 90,
    courier: "Aramex",
    price: 160,
    delivery: "3-4 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 91,
    courier: "DHL",
    price: 150,
    delivery: "2-3 days",
    discount: "8%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "India",
    toCountry: "UK",
  },
  {
    id: 92,
    courier: "FedEx",
    price: 140,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "USA",
  },
  {
    id: 93,
    courier: "UPS",
    price: 130,
    delivery: "4-5 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$6",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 94,
    courier: "TNT",
    price: 120,
    delivery: "5-6 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 95,
    courier: "Aramex",
    price: 135,
    delivery: "3-4 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 96,
    courier: "DHL",
    price: 160,
    delivery: "2-3 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 97,
    courier: "FedEx",
    price: 155,
    delivery: "3-4 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 98,
    courier: "UPS",
    price: 145,
    delivery: "4-5 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$6",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 99,
    courier: "TNT",
    price: 135,
    delivery: "5-7 days",
    discount: "6%",
    speed: "Economy",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 100,
    courier: "Aramex",
    price: 150,
    delivery: "3-4 days",
    discount: "11%",
    speed: "Fast",
    insurance: "$7",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 101,
    courier: "DHL",
    price: 101,
    delivery: "5-7 days",
    discount: "10%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 102,
    courier: "FedEx",
    price: 102,
    delivery: "2-3 days",
    discount: "11%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 103,
    courier: "UPS",
    price: 103,
    delivery: "3-4 days",
    discount: "12%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 104,
    courier: "TNT",
    price: 104,
    delivery: "4-5 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 105,
    courier: "Aramex",
    price: 105,
    delivery: "5-6 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 106,
    courier: "DHL",
    price: 106,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 107,
    courier: "FedEx",
    price: 107,
    delivery: "5-7 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 108,
    courier: "UPS",
    price: 108,
    delivery: "2-3 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 109,
    courier: "TNT",
    price: 109,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 110,
    courier: "Aramex",
    price: 110,
    delivery: "4-5 days",
    discount: "11%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 111,
    courier: "DHL",
    price: 111,
    delivery: "5-6 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 112,
    courier: "FedEx",
    price: 112,
    delivery: "3-5 days",
    discount: "5%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 113,
    courier: "UPS",
    price: 113,
    delivery: "5-7 days",
    discount: "6%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 114,
    courier: "TNT",
    price: 114,
    delivery: "2-3 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 115,
    courier: "Aramex",
    price: 115,
    delivery: "3-4 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 116,
    courier: "DHL",
    price: 116,
    delivery: "4-5 days",
    discount: "9%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 117,
    courier: "FedEx",
    price: 117,
    delivery: "5-6 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 118,
    courier: "UPS",
    price: 118,
    delivery: "3-5 days",
    discount: "11%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 119,
    courier: "TNT",
    price: 119,
    delivery: "5-7 days",
    discount: "12%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 120,
    courier: "Aramex",
    price: 120,
    delivery: "2-3 days",
    discount: "5%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 121,
    courier: "DHL",
    price: 121,
    delivery: "3-4 days",
    discount: "6%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 122,
    courier: "FedEx",
    price: 122,
    delivery: "4-5 days",
    discount: "7%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 123,
    courier: "UPS",
    price: 123,
    delivery: "5-6 days",
    discount: "8%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 124,
    courier: "TNT",
    price: 124,
    delivery: "3-5 days",
    discount: "9%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 125,
    courier: "Aramex",
    price: 125,
    delivery: "5-7 days",
    discount: "10%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 126,
    courier: "DHL",
    price: 126,
    delivery: "2-3 days",
    discount: "11%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 127,
    courier: "FedEx",
    price: 127,
    delivery: "3-4 days",
    discount: "12%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 128,
    courier: "UPS",
    price: 128,
    delivery: "4-5 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 129,
    courier: "TNT",
    price: 129,
    delivery: "5-6 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 130,
    courier: "Aramex",
    price: 130,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 131,
    courier: "DHL",
    price: 131,
    delivery: "5-7 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 132,
    courier: "FedEx",
    price: 132,
    delivery: "2-3 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 133,
    courier: "UPS",
    price: 133,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 134,
    courier: "TNT",
    price: 134,
    delivery: "4-5 days",
    discount: "11%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 135,
    courier: "Aramex",
    price: 135,
    delivery: "5-6 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 136,
    courier: "DHL",
    price: 136,
    delivery: "3-5 days",
    discount: "5%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 137,
    courier: "FedEx",
    price: 137,
    delivery: "5-7 days",
    discount: "6%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 138,
    courier: "UPS",
    price: 138,
    delivery: "2-3 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 139,
    courier: "TNT",
    price: 139,
    delivery: "3-4 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 140,
    courier: "Aramex",
    price: 140,
    delivery: "4-5 days",
    discount: "9%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 141,
    courier: "DHL",
    price: 141,
    delivery: "5-6 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 142,
    courier: "FedEx",
    price: 142,
    delivery: "3-5 days",
    discount: "11%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 143,
    courier: "UPS",
    price: 143,
    delivery: "5-7 days",
    discount: "12%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 144,
    courier: "TNT",
    price: 144,
    delivery: "2-3 days",
    discount: "5%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 145,
    courier: "Aramex",
    price: 145,
    delivery: "3-4 days",
    discount: "6%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 146,
    courier: "DHL",
    price: 146,
    delivery: "4-5 days",
    discount: "7%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 147,
    courier: "FedEx",
    price: 147,
    delivery: "5-6 days",
    discount: "8%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 148,
    courier: "UPS",
    price: 148,
    delivery: "3-5 days",
    discount: "9%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 149,
    courier: "TNT",
    price: 149,
    delivery: "5-7 days",
    discount: "10%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 150,
    courier: "Aramex",
    price: 100,
    delivery: "2-3 days",
    discount: "11%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 151,
    courier: "DHL",
    price: 101,
    delivery: "3-4 days",
    discount: "12%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 152,
    courier: "FedEx",
    price: 102,
    delivery: "4-5 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 153,
    courier: "UPS",
    price: 103,
    delivery: "5-6 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 154,
    courier: "TNT",
    price: 104,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 155,
    courier: "Aramex",
    price: 105,
    delivery: "5-7 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 156,
    courier: "DHL",
    price: 106,
    delivery: "2-3 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 157,
    courier: "FedEx",
    price: 107,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 158,
    courier: "UPS",
    price: 108,
    delivery: "4-5 days",
    discount: "11%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 159,
    courier: "TNT",
    price: 109,
    delivery: "5-6 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 160,
    courier: "Aramex",
    price: 110,
    delivery: "3-5 days",
    discount: "5%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 161,
    courier: "DHL",
    price: 111,
    delivery: "5-7 days",
    discount: "6%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 162,
    courier: "FedEx",
    price: 112,
    delivery: "2-3 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 163,
    courier: "UPS",
    price: 113,
    delivery: "3-4 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 164,
    courier: "TNT",
    price: 114,
    delivery: "4-5 days",
    discount: "9%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 165,
    courier: "Aramex",
    price: 115,
    delivery: "5-6 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 166,
    courier: "DHL",
    price: 116,
    delivery: "3-5 days",
    discount: "11%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 167,
    courier: "FedEx",
    price: 117,
    delivery: "5-7 days",
    discount: "12%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 168,
    courier: "UPS",
    price: 118,
    delivery: "2-3 days",
    discount: "5%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 169,
    courier: "TNT",
    price: 119,
    delivery: "3-4 days",
    discount: "6%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 170,
    courier: "Aramex",
    price: 120,
    delivery: "4-5 days",
    discount: "7%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 171,
    courier: "DHL",
    price: 121,
    delivery: "5-6 days",
    discount: "8%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 172,
    courier: "FedEx",
    price: 122,
    delivery: "3-5 days",
    discount: "9%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 173,
    courier: "UPS",
    price: 123,
    delivery: "5-7 days",
    discount: "10%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 174,
    courier: "TNT",
    price: 124,
    delivery: "2-3 days",
    discount: "11%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 175,
    courier: "Aramex",
    price: 125,
    delivery: "3-4 days",
    discount: "12%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 176,
    courier: "DHL",
    price: 126,
    delivery: "4-5 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 177,
    courier: "FedEx",
    price: 127,
    delivery: "5-6 days",
    discount: "6%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 178,
    courier: "UPS",
    price: 128,
    delivery: "3-5 days",
    discount: "7%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 179,
    courier: "TNT",
    price: 129,
    delivery: "5-7 days",
    discount: "8%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 180,
    courier: "Aramex",
    price: 130,
    delivery: "2-3 days",
    discount: "9%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 181,
    courier: "DHL",
    price: 131,
    delivery: "3-4 days",
    discount: "10%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 182,
    courier: "FedEx",
    price: 132,
    delivery: "4-5 days",
    discount: "11%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 183,
    courier: "UPS",
    price: 133,
    delivery: "5-6 days",
    discount: "12%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 184,
    courier: "TNT",
    price: 134,
    delivery: "3-5 days",
    discount: "5%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 185,
    courier: "Aramex",
    price: 135,
    delivery: "5-7 days",
    discount: "6%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 186,
    courier: "DHL",
    price: 136,
    delivery: "2-3 days",
    discount: "7%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 187,
    courier: "FedEx",
    price: 137,
    delivery: "3-4 days",
    discount: "8%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 188,
    courier: "UPS",
    price: 138,
    delivery: "4-5 days",
    discount: "9%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 189,
    courier: "TNT",
    price: 139,
    delivery: "5-6 days",
    discount: "10%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 190,
    courier: "Aramex",
    price: 140,
    delivery: "3-5 days",
    discount: "11%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 191,
    courier: "DHL",
    price: 141,
    delivery: "5-7 days",
    discount: "12%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 192,
    courier: "FedEx",
    price: 142,
    delivery: "2-3 days",
    discount: "5%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 193,
    courier: "UPS",
    price: 143,
    delivery: "3-4 days",
    discount: "6%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 194,
    courier: "TNT",
    price: 144,
    delivery: "4-5 days",
    discount: "7%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 195,
    courier: "Aramex",
    price: 145,
    delivery: "5-6 days",
    discount: "8%",
    speed: "Fast",
    insurance: "$8",
    fromCountry: "India",
    toCountry: "USA",
  },
  {
    id: 196,
    courier: "DHL",
    price: 146,
    delivery: "3-5 days",
    discount: "9%",
    speed: "Standard",
    insurance: "$9",
    fromCountry: "UAE",
    toCountry: "UK",
  },
  {
    id: 197,
    courier: "FedEx",
    price: 147,
    delivery: "5-7 days",
    discount: "10%",
    speed: "Economy",
    insurance: "$10",
    fromCountry: "USA",
    toCountry: "Canada",
  },
  {
    id: 198,
    courier: "UPS",
    price: 148,
    delivery: "2-3 days",
    discount: "11%",
    speed: "Fast",
    insurance: "$5",
    fromCountry: "UK",
    toCountry: "India",
  },
  {
    id: 199,
    courier: "TNT",
    price: 149,
    delivery: "3-4 days",
    discount: "12%",
    speed: "Standard",
    insurance: "$6",
    fromCountry: "Canada",
    toCountry: "UAE",
  },
  {
    id: 200,
    courier: "Aramex",
    price: 100,
    delivery: "4-5 days",
    discount: "5%",
    speed: "Economy",
    insurance: "$7",
    fromCountry: "India",
    toCountry: "USA",
  },
];
